# Generated by Django 6.0.4 on 2026-04-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.TextField()),
                ('column2', models.IntegerField(default=0)),
                ('column3', models.CharField(unique=True)),
                ('column4', models.DateField(auto_now=True)),
            ],
        ),
    ]
