# Generated by Django 6.0.4 on 2026-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Support Staff'), ('user', 'End User')], default='user', max_length=10),
        ),
    ]
