
# Generated by Django 6.0.4 on 2026-04-21 06:44
=======
# Generated by Django 6.0.4 on 2026-04-21 06:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_business', '0004_user_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
