# Generated by Django 6.0.4 on 2026-05-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_business', '0005_remove_user_is_rejected_remove_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
